services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /var/lib/redis/data
    environment:
      - REDIS_PASSWORD=redis1234
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
volumes:
  cache:
    driver: local